import java.util.Locale

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://repo.papermc.io/repository/maven-public/")
        maven("https://maven.neoforged.net/releases")
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

if (!file(".git").exists()) {
    val errorText = """

        =====================[ ERROR ]=====================
         The Eturlia project directory is not a properly cloned Git repository.

         In order to build Eturlia from source you must clone
         the repository using Git, not download a code
         zip from GitHub.

         See https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md
         for further information on building and modifying Paper and Forks.
        ===================================================
    """.trimIndent()
    error(errorText)
}

rootProject.name = "eturlia"

// Folia-API / Folia-Server are generated by paperweight (applyAllPatches).
for (name in listOf("Folia-API", "Folia-Server")) {
    val projName = name.lowercase(Locale.ENGLISH)
    include(projName)
    findProject(":$projName")!!.projectDir = file(name)
}

// NeoForge runtime module (resources + Eturlia mixins) and coremods (ICoreMod SPI)
include("neoforge")
include("neoforge:coremods")
project(":neoforge").projectDir = file("neoforge")
project(":neoforge:coremods").projectDir = file("neoforge/coremods")

gradle.lifecycle.beforeProject {
    val mcVersion = providers.gradleProperty("mcVersion").get().trim()
    val foliaVersionChannel = providers.gradleProperty("channel").get().trim()
    val foliaBuildNumber = providers.environmentVariable("BUILD_NUMBER").orNull?.trim()?.toInt()
    // Bukkit's version string has a fixed shape: <mc>-R<revision>[-<qualifier>]. Plugins parse it,
    // and a value like "1.21.1.local-SNAPSHOT" makes them throw — EssentialsX died on exactly that
    // with "Unknown-Version is not in valid version format. e.g. 1.8.8-R0.1", which disabled the
    // plugin and left every command it registers (help, list, ...) dead in the command map.
    val versionString = if (foliaBuildNumber == null) {
        "$mcVersion-R0.1-SNAPSHOT"
    } else {
        "$mcVersion-R0.1-$foliaBuildNumber-${foliaVersionChannel.lowercase()}"
    }
    version = versionString
}
